-- MySQL Script generated by MySQL Workbench
-- Sat Jan 30 13:25:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shizudaisei-finder
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shizudaisei-finder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shizudaisei-finder` DEFAULT CHARACTER SET utf8 ;
USE `shizudaisei-finder` ;

-- -----------------------------------------------------
-- Table `shizudaisei-finder`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shizudaisei-finder`.`users` (
  `id` VARCHAR(255) NOT NULL,
  `tweet_id` VARCHAR(255) NOT NULL,
  `content` VARCHAR(1023) NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shizudaisei-finder`.`friendships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shizudaisei-finder`.`friendships` (
  `from` VARCHAR(255) NOT NULL,
  `to` VARCHAR(255) NOT NULL,
  `created` DATETIME NULL,
  PRIMARY KEY (`from`, `to`),
  INDEX `fk_friendships_users1_idx` (`to` ASC) VISIBLE,
  CONSTRAINT `fk_friendships_users`
    FOREIGN KEY (`from`)
    REFERENCES `shizudaisei-finder`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friendships_users1`
    FOREIGN KEY (`to`)
    REFERENCES `shizudaisei-finder`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
